export const TITLES = [
  "Teacher",
  "Principal",
  "Assistant Principal",
  "Counselor",
  "Supervisor",
  "Coordinator",
  "Dean",
  "Librarian",
  "Nurse",
  "Security Staff",
  "Administrative Assistant",
  "Specialist",
  "Coach",
  "Substitute Teacher",
];

export const DEPARTMENTS = [
  "Administration",
  "Mathematics",
  "Science",
  "English",
  "History",
  "Social Studies",
  "Physical Education",
  "Arts",
  "Music",
  "Computer Science",
  "Foreign Languages",
  "Special Education",
  "Counseling",
  "Library",
  "Health Services",
  "Security",
  "Facilities",
  "Transportation",
  "Food Services",
];
